### PR TITLE
Setup CI

### PR DESCRIPTION
**Pull request by cuducos**
This PR brings in @amadeu01's contribution from #29 together with some ideas he drafted in #41.

As #29 was already good to merge, but coverage was missing, and as @amadeu01 said he was kind of busy, I implemented coverage myself to get this contribution quicker to the `master` branch.

### CODE REVIEW

**Comment by cuducos** [comment]
I'd like to see Codecov as a check, but I'm afraid I couldn't set it up. Maybe by merging `codecov.yml` to `master` it works. Let's see ; )

**Comment by amadeu01** [comment]
@cuducos thanks a lot! 

Sorry for my delay! I got messed up with my personal and job tasks. 

Thanks for finishing the job 😄

**Comment by amadeu01** [comment]
> I'd like to see Codecov as a check, but I'm afraid I couldn't set it up. Maybe by merging codecov.yml to master it works. Let's see ; )

Do you mean, the codecov giving comments about the code?

**Comment by cuducos** [comment]
> Sorry for my delay!

No need to be sorry — you're a volunteer after all ❤️

> Do you mean, the codecov giving comments about the code?

No. This is too verbose. I [explicitly configured it **not** to comment](https://github.com/okfn-brasil/perfil/pull/43/files#diff-8bc9db6adba7208e25c96be322351063R9) and actually deleted the comment:

image


What I meant is a check in this list (which is now working, not sure why):

image

My best guess is that it only starts when triggered by Travis.

Anyway. If a check fails, we can click and know more about why it fails (no need for the vebrose comments IMHO).

Ready for code review ; )

**Pull request merged**
